// packages/solidjs/src/components/contents/index.tsx
import { CHOICE_SEPARATOR, contentsStore } from "@inkweave/core";
import { createSignal, For, onCleanup } from "solid-js";
import { useStory } from "../story";
import styles from "./styles.module.css";

const ContentsComponent = () => {
  const ink = useStory();
  const [contents, setContents] = createSignal([...contentsStore.getState().contents]);

  const unsub = contentsStore.subscribe((state) => {
    setContents([...state.contents]);
  });
  onCleanup(unsub);

  const lineDelay = () => (ink.options.linedelay as number) ?? 0.05;

  const visibleLines = () => {
    const v = ink.visibleLines;
    return typeof v === "number" ? v : contents().length;
  };

  return (
    <section class={`inkweave-contents ${styles.contents}`}>
      <For each={contents()}>
        {(item, i) => {
          const vl = visibleLines();
          const ld = lineDelay();
          const delay = `${(i() > vl ? i() - vl : 0) * ld}s`;
          const isDivider = item.text === CHOICE_SEPARATOR;

          if (isDivider) {
            return (
              <div
                class={ld > 0 ? styles.fade : ""}
                style={ld > 0 ? ({ "--delay": delay } as Record<string, string>) : { opacity: "1" }}
              >
                <hr class="inkweave-divider" />
              </div>
            );
          }

          const combinedClasses = ["inkweave-content-line"];
          if (item.classes && item.classes.length > 0) {
            combinedClasses.push(...item.classes);
          }
          if (ld > 0 && styles.fade) {
            combinedClasses.push(styles.fade);
          }

          return (
            <div
              style={ld > 0 ? ({ "--delay": delay } as Record<string, string>) : { opacity: "1" }}
              class={combinedClasses.join(" ")}
            >
              <p>{item.text}</p>
            </div>
          );
        }}
      </For>
    </section>
  );
};

export default ContentsComponent;

// packages/react/src/components/contents/index.tsx
import { CHOICE_SEPARATOR, type ContentItem, contentsStore } from "@inkweave/core";
import { type CSSProperties, memo, useMemo } from "react";
import { useStory } from "../story";
import styles from "./styles.module.css";

const ContentsComponent = () => {
  const ink = useStory();
  const contents = contentsStore((state) => state.contents);
  const visibleLines = typeof ink.visibleLines === "number" ? ink.visibleLines : contents.length;
  const lineDelay = (ink.options.linedelay as number) ?? 0.05;

  const renderedContents = useMemo(() => {
    return contents.map((item: ContentItem, i: number) => {
      const isDivider = item.text === CHOICE_SEPARATOR;
      const key = isDivider ? `divider_${i}` : `line_${i}_${item.text.slice(0, 20)}`;
      const hasFade = lineDelay > 0;
      const delay = `${(i > visibleLines ? i - visibleLines : 0) * lineDelay}s`;

      if (isDivider) {
        return (
          <div
            key={key}
            className={hasFade ? styles.fade : ""}
            style={hasFade ? ({ "--delay": delay } as CSSProperties) : { opacity: "1" }}
          >
            <hr className="inkweave-divider" />
          </div>
        );
      }

      const combinedClasses = ["inkweave-content-line"];
      if (item.classes && item.classes.length > 0) {
        combinedClasses.push(...item.classes);
      }
      if (hasFade && styles.fade) {
        combinedClasses.push(styles.fade);
      }

      return (
        <div
          key={key}
          className={combinedClasses.join(" ")}
          style={hasFade ? ({ "--delay": delay } as CSSProperties) : { opacity: "1" }}
        >
          <p>{item.text}</p>
        </div>
      );
    });
  }, [contents, visibleLines, lineDelay]);

  return <section className={`inkweave-contents ${styles.contents}`}>{renderedContents}</section>;
};

export default memo(ContentsComponent);
