// packages/plugins/src/image/solidjs/Image.tsx
import type { JSX } from "solid-js";
import { createEffect, createSignal, onCleanup, Show } from "solid-js";
import { useStoryImage } from "../index";
import styles from "./Image.module.css";

interface ImageProps {
  class?: string;
  fallback?: JSX.Element;
}

const ImageComponent = (props: ImageProps) => {
  const [image, setImage] = createSignal(useStoryImage.getState().image);
  const [hasError, setHasError] = createSignal(false);

  createEffect(() => {
    const unsub = useStoryImage.subscribe((state) => {
      setImage(state.image);
      setHasError(false);
    });
    onCleanup(unsub);
  });

  const handleError = () => {
    setHasError(true);
    console.warn(`InkWeave: Failed to load image: ${image()}`);
  };

  const handleLoad = () => {
    setHasError(false);
  };

  const containerClassName = `${styles.container} ${props.class || ""}`.trim();

  return (
    <Show when={image()}>
      <Show
        when={!hasError()}
        fallback={
          <Show when={props.fallback}>
            <div id="inkweave-image" class={containerClassName}>
              {props.fallback}
            </div>
          </Show>
        }
      >
        <div id="inkweave-image" class={containerClassName}>
          <img src={image() ?? ""} alt="" onError={handleError} onLoad={handleLoad} />
        </div>
      </Show>
    </Show>
  );
};

export default ImageComponent;

// packages/plugins/src/image/react/Image.tsx
import { memo, useCallback, useEffect, useRef, useState } from "react";
import { useStoryImage } from "../index";
import styles from "./Image.module.css";

interface ImageProps {
  className?: string;
  fallback?: React.ReactNode;
}

const ImageComponent: React.FC<ImageProps> = ({ className = "", fallback = null }) => {
  const image = useStoryImage((state) => state.image);
  const [hasError, setHasError] = useState(false);

  useEffect(() => {
    setHasError(false);
  }, [image]);

  const imageRef = useRef(image);
  imageRef.current = image;

  const handleError = useCallback(() => {
    setHasError(true);
    console.warn(`InkWeave: Failed to load image: ${imageRef.current}`);
  }, []);

  const handleLoad = useCallback(() => {
    setHasError(false);
  }, []);

  const containerClassName = `${styles.container} ${className}`.trim();

  if (!image) return null;

  if (hasError) {
    return fallback ? (
      <div id="inkweave-image" className={containerClassName}>
        {fallback}
      </div>
    ) : null;
  }

  return (
    <div id="inkweave-image" className={containerClassName}>
      <img src={image} alt="" onError={handleError} onLoad={handleLoad} />
    </div>
  );
};

export default memo(ImageComponent);
