// packages/plugins/src/image/solidjs/Image.tsx
import type { JSX } from "solid-js";
import { createEffect, createSignal, onCleanup, Show } from "solid-js";
import { useStoryImage } from "../index";
import styles from "./Image.module.css";

interface ImageProps {
  class?: string;
  fallback?: JSX.Element;
}

const ImageComponent = (props: ImageProps) => {
  const [image, setImage] = createSignal(useStoryImage.getState().image);
  const [hasError, setHasError] = createSignal(false);

  createEffect(() => {
    const unsub = useStoryImage.subscribe((state) => {
      setImage(state.image);
      setHasError(false);
    });
    onCleanup(unsub);
  });

  const handleError = () => {
    setHasError(true);
    console.warn(`InkWeave: Failed to load image: ${image()}`);
  };

  const handleLoad = () => {
    setHasError(false);
  };

  const containerClassName = `${styles.container} ${props.class || ""}`.trim();

  return (
    <Show when={image()}>
      <Show
        when={!hasError()}
        fallback={
          <Show when={props.fallback}>
            <div id="inkweave-image" class={containerClassName}>
              {props.fallback}
            </div>
          </Show>
        }
      >
        <div id="inkweave-image" class={containerClassName}>
          <img src={image() ?? ""} alt="" onError={handleError} onLoad={handleLoad} />
        </div>
      </Show>
    </Show>
  );
};

export default ImageComponent;

// packages/plugins/src/image/svelte/Image.svelte
<script lang="ts">
import { onMount } from "svelte";
import { useStoryImage } from "../index";

interface Props {
  class?: string;
}

let { class: className = "" }: Props = $props();

let image = $state("");
let hasError = $state(false);

onMount(() => {
  const unsub = useStoryImage.subscribe((state) => {
    image = state.image;
    hasError = false;
  });
  return unsub;
});

function handleError() {
  hasError = true;
  console.warn(`InkWeave: Failed to load image: ${image}`);
}

function handleLoad() {
  hasError = false;
}
</script>

{#if image && !hasError}
  <div id="inkweave-image" class="inkweave-image-container {className}">
    <img src={image} alt="" onerror={handleError} onload={handleLoad} />
  </div>
{/if}

<style>
  :global(.inkweave-image-container) {
    display: flex;
    justify-content: center;
    margin-bottom: 1rem;
    flex-shrink: 0;
  }

  :global(.inkweave-image-container img) {
    max-width: 100%;
    max-height: 400px;
    border-radius: 8px;
    object-fit: contain;
  }
</style>
