// packages/solidjs/src/components/command-bar/index.tsx
import { CommandRegistry, type InkStory, type TranslationFunction } from "@inkweave/core";
import { createComponent, createEffect, createMemo, createSignal, type JSX } from "solid-js";
import CommandButton from "./CommandButton";
import style from "./styles.module.css";

const translate: TranslationFunction = (key) => {
  if (!key) return undefined;
  return CommandRegistry.getTranslation(key) ?? key;
};

interface CommandBarProps {
  ink: InkStory;
  class?: string;
  buttonClass?: string;
  modalClass?: string;
  t?: TranslationFunction;
}

const CommandBar = (props: CommandBarProps) => {
  const t = (key: string | undefined) => {
    if (!props.t) return translate(key);
    return props.t(key) ?? translate(key);
  };

  const [modalId, setModalId] = createSignal<string | null>(null);
  let modalRef: HTMLDialogElement | undefined;

  const closeModal = () => {
    setModalId(null);
    if (modalRef) {
      modalRef.close();
    }
  };

  const handleBackdropClick = (e: MouseEvent) => {
    if (e.target === e.currentTarget && modalRef?.open) {
      closeModal();
    }
  };

  const handleKeyUp = (e: KeyboardEvent) => {
    if (e.key === "Escape" && modalRef?.open) {
      closeModal();
    }
  };

  const setActiveModal = (commandId: string) => {
    setModalId(commandId);
  };

  createEffect(() => {
    const id = modalId();
    if (id && modalRef) {
      modalRef.showModal();
    }
    return () => {
      if (modalRef?.open) {
        modalRef.close();
      }
    };
  });

  const modalContent = createMemo((): JSX.Element | null => {
    const id = modalId();
    if (!id) return null;
    const command = CommandRegistry.get(id);
    if (command?.getModalContent) {
      const content = command.getModalContent({
        ink: props.ink,
        onClose: closeModal,
        t,
      });

      // Handle { component, props } objects from plugins
      if (content && typeof content === "object" && "component" in content && "props" in content) {
        const { component: Comp, props: compProps } = content as {
          component: (props: Record<string, unknown>) => JSX.Element;
          props: Record<string, unknown>;
        };
        return createComponent(Comp, compProps);
      }

      // Handle DOM elements（HTMLElement 继承自 Node，属于 JSX.Element 的合法成员）
      if (content instanceof HTMLElement) {
        return content as JSX.Element;
      }

      return content as JSX.Element;
    }
    return null;
  });

  const sortedButtons = createMemo(() =>
    CommandRegistry.getAll()
      .sort((a, b) => (a.priority ?? 0) - (b.priority ?? 0))
      .map((command) => (
        <CommandButton
          commandId={command.id}
          ink={props.ink}
          class={props.buttonClass}
          onRequestOpenModal={command.getModalContent ? setActiveModal : undefined}
          t={t}
        />
      )),
  );

  const modalTitle = createMemo(() => {
    const id = modalId();
    if (!id) return "Command";
    const command = CommandRegistry.get(id);
    return t(command?.title) ?? "Command";
  });

  return (
    <>
      <div class={props.class}>{sortedButtons()}</div>
      <dialog
        ref={(el) => {
          modalRef = el;
        }}
        onclose={closeModal}
        onClick={handleBackdropClick}
        onKeyUp={handleKeyUp}
        class={props.modalClass}
      >
        <div id="inkweave-modal-header" class={style.header}>
          <span id="inkweave-modal-title" class={style.title}>
            {modalTitle()}
          </span>
          <button
            type="button"
            id="inkweave-modal-close"
            class={style.close}
            onClick={closeModal}
            aria-label="Close"
          >
            ×
          </button>
        </div>
        <div id="inkweave-modal-body" class={style.body}>
          {modalContent()}
        </div>
      </dialog>
    </>
  );
};

export default CommandBar;

// packages/svelte/src/CommandBar.svelte
<script lang="ts">
import type { Command, InkStory, TranslationFunction } from "@inkweave/core";
import { CommandRegistry } from "@inkweave/core";
import { mount, unmount } from "svelte";

interface Props {
  ink: InkStory;
  class?: string;
  buttonClass?: string;
  modalClass?: string;
  t?: TranslationFunction;
}

let { ink, class: className = "", buttonClass = "", modalClass = "", t }: Props = $props();

const translate: TranslationFunction = (key) => {
  if (!key) return undefined;
  if (t) return t(key) ?? CommandRegistry.getTranslation(key) ?? key;
  return CommandRegistry.getTranslation(key) ?? key;
};

let modalRef = $state<HTMLDialogElement | null>(null);
let activeCommand = $state<Command | null>(null);
let currentModalInstance: Record<string, unknown> | null = null;

const modalTitle = $derived(
  activeCommand ? (translate(activeCommand.title) ?? "Command") : "Command",
);

function openModal(command: Command) {
  activeCommand = command;
}

function closeModal() {
  activeCommand = null;
  if (currentModalInstance) {
    unmount(currentModalInstance);
    currentModalInstance = null;
  }
  modalRef?.close();
}

// Mount modal content when activeCommand changes
$effect(() => {
  if (activeCommand && modalRef) {
    // Clean up previous instance
    if (currentModalInstance) {
      unmount(currentModalInstance);
      currentModalInstance = null;
    }
    const body = modalRef.querySelector("#inkweave-modal-body");
    if (body && activeCommand.getModalContent) {
      body.innerHTML = "";
      const content = activeCommand.getModalContent({
        ink,
        onClose: closeModal,
        t: translate,
      }) as { component: never; props: Record<string, unknown> };
      currentModalInstance = mount(content.component, {
        target: body,
        props: content.props,
      });
    }
    modalRef.showModal();
  }
});

function handleCommand(command: Command) {
  if (command.getModalContent) {
    openModal(command);
  } else {
    CommandRegistry.execute(command.id, ink);
  }
}

function handleBackdropClick(e: MouseEvent) {
  if (e.target === modalRef && modalRef?.open) {
    closeModal();
  }
}

function handleKeyDown(e: KeyboardEvent) {
  if (e.key === "Escape" && modalRef?.open) {
    closeModal();
  }
}

const sortedCommands = $derived(
  CommandRegistry.getAll().sort((a, b) => (a.priority ?? 0) - (b.priority ?? 0)),
);
</script>

<div class={className}>
  {#each sortedCommands as command (command.id)}
    <button
      type="button"
      class="inkweave-command-btn {buttonClass}"
      onclick={() => handleCommand(command)}
      title={translate(command.name)}
      aria-label={translate(command.description)}
    >
      {#if command.icon}
        <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
          <path d={command.icon} />
        </svg>
      {:else}
        {translate(command.name)}
      {/if}
    </button>
  {/each}
</div>
<dialog
  bind:this={modalRef}
  onclose={closeModal}
  onclick={handleBackdropClick}
  onkeydown={handleKeyDown}
  class={modalClass}
>
  <div id="inkweave-modal-header" class="header">
    <span id="inkweave-modal-title" class="title">{modalTitle}</span>
    <button
      type="button"
      id="inkweave-modal-close"
      class="close"
      onclick={closeModal}
      aria-label="Close"
    >
      ×
    </button>
  </div>
  <div id="inkweave-modal-body" class="body"></div>
</dialog>

<style>
  .header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 0.5rem 1rem;
  }

  .body {
    display: flex;
    flex-direction: column;
  }

  .close {
    background: none;
    border: none;
    font-size: 1.3rem;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .close:hover {
    opacity: 0.7;
  }
</style>
