// packages/solidjs/src/components/story/index.tsx
import type { InkStory } from "@inkweave/core";
import { createContext, type JSX, onMount, useContext } from "solid-js";
import Choices from "../choices";
import Contents from "../contents";
import styles from "./styles.module.css";

const StoryContext = createContext<InkStory | null>(null);

export const useStory = () => {
  const ink = useContext(StoryContext);
  if (!ink) {
    throw new Error("useStory must be used within StoryProvider");
  }
  return ink;
};

interface StoryProviderProps {
  ink: InkStory;
  children?: JSX.Element;
}

export const StoryProvider = (props: StoryProviderProps) => {
  return <StoryContext.Provider value={props.ink}>{props.children}</StoryContext.Provider>;
};

interface StoryProps {
  ink: InkStory;
  children?: JSX.Element;
  class?: string;
  onInit?: (ink: InkStory) => void;
}

const Story = (props: StoryProps) => {
  onMount(() => {
    props.ink.continue();
    props.onInit?.(props.ink);
  });

  return (
    <StoryProvider ink={props.ink}>
      <div id="inkweave-story" class={`${styles.story} ${props.class || ""}`} data-inkweave="story">
        {props.children}
        <Contents />
        <Choices />
      </div>
    </StoryProvider>
  );
};

export default Story;

// packages/react/src/components/Story/index.tsx
import { memo, useEffect, useRef, createContext, useContext } from 'react';
import type { InkStory } from '@inkweave/core';
import Contents from '../Contents';
import Choices from '../Choices';
import styles from './styles.module.css';

const StoryContext = createContext<InkStory | null>(null);

export const useStory = () => {
	const ink = useContext(StoryContext);
	if (!ink) {
		throw new Error('useStory must be used within StoryProvider');
	}
	return ink;
};

interface StoryProviderProps {
	ink: InkStory;
	children?: React.ReactNode;
}

export const StoryProvider: React.FC<StoryProviderProps> = ({
	ink,
	children,
}) => {
	return (
		<StoryContext.Provider value={ink}>
			{children}
		</StoryContext.Provider>
	);
};

interface StoryProps {
	ink: InkStory;
	children?: React.ReactNode;
	className?: string;
	onInit?: (ink: InkStory) => void;
}

const StoryComponent: React.FC<StoryProps> = ({
	ink,
	children,
	className = '',
	onInit,
}) => {
	const onInitRef = useRef(onInit);
	onInitRef.current = onInit;

	useEffect(() => {
		ink.restart();
		onInitRef.current?.(ink);
	}, [ink]);

	return (
		<StoryProvider ink={ink}>
			<div
				className={`inkweave-story ${styles.story} ${className}`.trim()}
				data-inkweave="story"
			>
				{children}
				<Contents />
				<Choices />
			</div>
		</StoryProvider>
	);
};

export default memo(StoryComponent);
