// packages/solidjs/src/components/choices/index.tsx
import { type Choice, ChoiceRegistry as ChoiceRegistryClass, choicesStore } from "@inkweave/core";
import { createMemo, createSignal, For, onCleanup, onMount } from "solid-js";
import type { ChoiceComponent } from "../../types";
import { useStory } from "../story";
import styles from "./styles.module.css";

export const ChoiceRegistry = new ChoiceRegistryClass<ChoiceComponent>();

interface ChoiceItemProps {
  choice: Choice;
  index: number;
  onClick: (index: number) => void;
}

const ChoiceItem = (props: ChoiceItemProps) => {
  const classList = () => {
    const list = [...props.choice.classes, styles.button, "inkweave-choice"];
    if (props.choice.type === "unclickable" && styles.disabled) {
      list.push(styles.disabled);
    }
    return [...new Set(list)].join(" ");
  };

  const handleClick = () => {
    if (props.choice.type !== "unclickable") {
      props.onClick(props.choice.index);
    }
  };

  const Component = ChoiceRegistry.get(props.choice.type);

  if (Component) {
    return (
      <li class={styles.item} style={{ "--index": props.index } as Record<string, string | number>}>
        <Component choice={props.choice} onClick={handleClick} class={classList()}>
          {props.choice.text}
        </Component>
      </li>
    );
  }

  return (
    <li class={styles.item} style={{ "--index": props.index } as Record<string, string | number>}>
      <a
        onClick={handleClick}
        class={classList()}
        aria-disabled={props.choice.type === "unclickable"}
      >
        {props.choice.text}
      </a>
    </li>
  );
};

const ChoicesComponent = () => {
  const ink = useStory();
  const [version, setVersion] = createSignal(0);

  onMount(() => {
    setVersion(1);
    const unsub = choicesStore.subscribe(() => {
      setVersion((v) => v + 1);
    });
    onCleanup(unsub);
  });

  const choices = createMemo(() => {
    version();
    return choicesStore.getState().choices;
  });

  const canShow = () => (typeof ink.choicesCanShow === "boolean" ? ink.choicesCanShow : true);

  const handleClick = (index: number) => {
    ink.choose(index);
  };

  return (
    <ul
      data-inkweave="choices"
      class={`inkweave-choices ${styles.choices}`}
      style={{ visibility: canShow() ? "visible" : "hidden" }}
    >
      <For each={choices()}>
        {(choice, index) => <ChoiceItem choice={choice} index={index()} onClick={handleClick} />}
      </For>
    </ul>
  );
};

export default ChoicesComponent;

// packages/react/src/components/Choices.tsx
import { memo, createElement, useCallback } from 'react';
import { Choice, choicesStore } from '@inkweave/core';
import { useStory } from './Story';
import { ChoiceComponents } from './ChoiceComponents';

interface ChoiceItemProps {
	choice: Choice;
	index: number;
	onClick: (index: number) => void;
	className: string;
}

const ChoiceItem: React.FC<ChoiceItemProps> = memo(({ choice, index, onClick, className }) => {
	const handleClick = useCallback(() => {
		if (choice.type !== 'unclickable') {
			onClick(choice.index);
		}
	}, [choice.index, choice.type, onClick]);

	const Component = ChoiceComponents.get(choice.type);
	if (Component) {
		return (
			<li style={{ '--index': index } as React.CSSProperties}>
				{createElement(Component, {
					onClick: handleClick,
					className,
					val: choice.val,
					children: choice.text,
				})}
			</li>
		);
	}

	return (
		<li style={{ '--index': index } as React.CSSProperties}>
			<a
				onClick={handleClick}
				className={`${className} ${choice.type === 'unclickable' ? 'disabled' : ''}`}
				aria-disabled={choice.type === 'unclickable'}
			>
				{choice.text}
			</a>
		</li>
	);
});
ChoiceItem.displayName = 'ChoiceItem';

interface ChoicesProps {
	onClick?: (index: number) => void;
	className?: string;
}

const ChoicesComponent: React.FC<ChoicesProps> = ({
	onClick,
	className = 'inkweave-btn',
}) => {
	const ink = useStory();
	const choices = choicesStore((state) => state.choices);
	const inkRecord = ink as unknown as Record<string, unknown>;
	const canShow =
		inkRecord && 'choicesCanShow' in inkRecord
			? (inkRecord.choicesCanShow as boolean)
			: true;

	const handleClick = useCallback((index: number) => {
		onClick?.(index);
		ink.choose(index);
	}, [ink, onClick]);

	return (
		<ul
			id="inkweave-choices"
			key={canShow.toString()}
			style={{ visibility: canShow ? 'visible' : 'hidden' }}
		>
			{choices.map((choice: Choice, index: number) => (
				<ChoiceItem
					key={choice.index}
					choice={choice}
					index={index}
					onClick={handleClick}
					className={className}
				/>
			))}
		</ul>
	);
};

export default memo(ChoicesComponent);
