// packages/solidjs/src/components/contents/index.tsx
import { CHOICE_SEPARATOR, type ContentItem, contentsStore } from "@inkweave/core";
import { createMemo, createSignal, onCleanup } from "solid-js";
import { useStory } from "../story";
import styles from "./styles.module.css";

const ContentsComponent = () => {
  const ink = useStory();
  const [contents, setContents] = createSignal([...contentsStore.getState().contents]);

  const unsub = contentsStore.subscribe((state) => {
    setContents([...state.contents]);
  });
  onCleanup(unsub);

  const lineDelay = () => (ink.options.linedelay as number) ?? 0.05;

  const visibleLines = () => {
    const v = contentsStore.getState().visibleLines;
    return v ?? (lineDelay() > 0 ? -1 : contents().length);
  };

  const renderedContents = createMemo(() => {
    const ld = lineDelay();
    const vl = visibleLines();
    const items = contents();

    return items.map((item: ContentItem, i: number) => {
      const delay = `${(i > vl ? i - vl : 0) * ld}s`;
      const isDivider = item.text === CHOICE_SEPARATOR;

      if (isDivider) {
        return (
          <div
            class={ld > 0 ? styles.fade : ""}
            style={ld > 0 ? ({ "--delay": delay } as Record<string, string>) : { opacity: "1" }}
          >
            <hr class="inkweave-divider" />
          </div>
        );
      }

      return (
        <div
          style={ld > 0 ? ({ "--delay": delay } as Record<string, string>) : { opacity: "1" }}
          class={["inkweave-content-line", ...(item.classes ?? []), ld > 0 && styles.fade]
            .filter(Boolean)
            .join(" ")}
        >
          <p>{item.text}</p>
        </div>
      );
    });
  });

  return <section class={`inkweave-contents ${styles.contents}`}>{renderedContents()}</section>;
};

export default ContentsComponent;

// packages/react/src/components/Contents.tsx
import { memo, useMemo, CSSProperties } from 'react';
import { CHOICE_SEPARATOR, contentsStore } from '@inkweave/core';
import { useStory } from './Story';

interface ContentsProps {
	lineDelay?: number;
	className?: string;
}

const ContentsComponent: React.FC<ContentsProps> = ({
	lineDelay = 0.05,
	className = '',
}) => {
	const ink = useStory();
	const contents = contentsStore((state) => state.contents);
	const inkRecord = ink as unknown as Record<string, unknown>;
	const visibleLines =
		inkRecord?.visibleLines != undefined
			? (inkRecord.visibleLines as number)
			: contents.length;

	const renderedContents = useMemo(() => {
		return contents.map((item: string, i: number) => {
			const style: CSSProperties = {
				'--delay': `${
					(i > visibleLines ? i - visibleLines : 0) * lineDelay
				}s`,
			} as CSSProperties & { '--delay': string };

			const isDivider = item === CHOICE_SEPARATOR;
			const key = isDivider ? `divider_${i}` : `line_${i}_${item.slice(0, 20)}`;

			if (isDivider) {
				return (
					<div key={key} style={style}>
						<hr className="inkweave-divider" />
					</div>
				);
			}

			return (
				<div key={key} style={style}>
					<p className={className}>{item}</p>
				</div>
			);
		});
	}, [contents, visibleLines, lineDelay, className]);

	return (
		<section id="inkweave-contents">
			{renderedContents}
		</section>
	);
};

export default memo(ContentsComponent);
