// packages/solidjs/src/components/status-bar/index.tsx
import type { InkStory, StatusBarConfig } from "@inkweave/core";
import { variablesStore } from "@inkweave/core";
import { createMemo, createSignal, type JSX, onCleanup, onMount } from "solid-js";
import styles from "./styles.module.css";

interface StatusBarProps {
  ink: InkStory;
  variables: StatusBarConfig[];
  class?: string;
}

const StatusBar = (props: StatusBarProps): JSX.Element => {
  const [version, setVersion] = createSignal(0);

  onMount(() => {
    setVersion(1);
    const unsub = variablesStore.subscribe(() => setVersion((v) => v + 1));
    onCleanup(unsub);
  });

  const allVars = createMemo(() => {
    version();
    return variablesStore.getState().variables;
  });

  const getValue = (key: string): number => {
    const raw = allVars().get(key);
    return typeof raw === "number" ? raw : 0;
  };

  return (
    <div id="inkweave-status-bar" class={`${styles.bar} ${props.class || ""}`}>
      {props.variables.map((cfg) => {
        if (cfg.display === "number") {
          const value = getValue(cfg.key);
          return (
            <div class={styles.item}>
              <span class={styles.label}>{cfg.label}</span>
              <span class={styles.value}>{Math.round(value)}</span>
            </div>
          );
        }

        const percent = variablesStore.getState().getPercent(cfg.key);
        return (
          <div class={styles.item}>
            <span class={styles.label}>{cfg.label}</span>
            <div class={styles.track}>
              <div class={styles.fill} style={{ width: `${percent}%` }} />
            </div>
          </div>
        );
      })}
    </div>
  );
};

export default StatusBar;

// packages/react/src/components/status-bar/index.tsx
import type { InkStory, StatusBarConfig } from "@inkweave/core";
import { variablesStore } from "@inkweave/core";
import { memo, useCallback } from "react";
import styles from "./styles.module.css";

interface StatusBarProps {
  ink: InkStory;
  variables: StatusBarConfig[];
  class?: string;
}

const StatusBar: React.FC<StatusBarProps> = ({ ink: _ink, variables, class: className }) => {
  const allVars = variablesStore((s) => s.variables);

  const renderItem = useCallback(
    (cfg: (typeof variables)[number]) => {
      const rawValue = allVars.get(cfg.key);
      const value = typeof rawValue === "number" ? rawValue : 0;

      if (cfg.display === "number") {
        return (
          <div key={cfg.key} className={styles.item}>
            <span className={styles.label}>{cfg.label}</span>
            <span className={styles.value}>{Math.round(value)}</span>
          </div>
        );
      }

      const percent = variablesStore.getState().getPercent(cfg.key);
      return (
        <div key={cfg.key} className={styles.item}>
          <span className={styles.label}>{cfg.label}</span>
          <div className={styles.track}>
            <div className={styles.fill} style={{ width: `${percent}%` }} />
          </div>
        </div>
      );
    },
    [allVars],
  );

  return (
    <div id="inkweave-status-bar" className={[styles.bar, className].filter(Boolean).join(" ")}>
      {variables.map(renderItem)}
    </div>
  );
};

StatusBar.displayName = "StatusBar";
export default memo(StatusBar);
