// packages/solidjs/src/components/choices/index.tsx
import { type Choice, ChoiceRegistry as ChoiceRegistryClass, choicesStore } from "@inkweave/core";
import { createMemo, createSignal, For, onCleanup, onMount } from "solid-js";
import type { ChoiceComponent } from "../../types";
import { useStory } from "../story";
import styles from "./styles.module.css";

export const ChoiceRegistry = new ChoiceRegistryClass<ChoiceComponent>();

interface ChoiceItemProps {
  choice: Choice;
  index: number;
  onClick: (index: number) => void;
}

const ChoiceItem = (props: ChoiceItemProps) => {
  const classList = () => {
    const list = [...props.choice.classes, styles.button, "inkweave-choice"];
    if (props.choice.type === "unclickable" && styles.disabled) {
      list.push(styles.disabled);
    }
    return [...new Set(list)].join(" ");
  };

  const handleClick = () => {
    if (props.choice.type !== "unclickable") {
      props.onClick(props.choice.index);
    }
  };

  const Component = ChoiceRegistry.get(props.choice.type);

  if (Component) {
    return (
      <li class={styles.item} style={{ "--index": props.index } as Record<string, string | number>}>
        <Component choice={props.choice} onClick={handleClick} class={classList()}>
          {props.choice.text}
        </Component>
      </li>
    );
  }

  return (
    <li class={styles.item} style={{ "--index": props.index } as Record<string, string | number>}>
      <a
        onClick={handleClick}
        class={classList()}
        aria-disabled={props.choice.type === "unclickable"}
      >
        {props.choice.text}
      </a>
    </li>
  );
};

const ChoicesComponent = () => {
  const ink = useStory();
  const [version, setVersion] = createSignal(0);

  onMount(() => {
    setVersion(1);
    const unsub = choicesStore.subscribe(() => {
      setVersion((v) => v + 1);
    });
    onCleanup(unsub);
  });

  const choices = createMemo(() => {
    version();
    return choicesStore.getState().choices;
  });

  const canShow = () => (typeof ink.choicesCanShow === "boolean" ? ink.choicesCanShow : true);

  const handleClick = (index: number) => {
    ink.choose(index);
  };

  return (
    <ul
      data-inkweave="choices"
      class={`inkweave-choices ${styles.choices}`}
      style={{ visibility: canShow() ? "visible" : "hidden" }}
    >
      <For each={choices()}>
        {(choice, index) => <ChoiceItem choice={choice} index={index()} onClick={handleClick} />}
      </For>
    </ul>
  );
};

export default ChoicesComponent;

// packages/react/src/components/choices/index.tsx
import { type Choice, ChoiceRegistry as ChoiceRegistryClass, choicesStore } from "@inkweave/core";
import { createElement, memo, useCallback, useRef } from "react";
import type { ChoiceComponent } from "../../types";
import { useStory } from "../story";
import styles from "./styles.module.css";

export const ChoiceRegistry = new ChoiceRegistryClass<ChoiceComponent>();

interface ChoiceItemProps {
  choice: Choice;
  index: number;
  onClick: (index: number) => void;
}

const ChoiceItem: React.FC<ChoiceItemProps> = memo(
  ({ choice, index, onClick }) => {
    const handleClick = useCallback(() => {
      if (choice.type !== "unclickable") {
        onClick(choice.index);
      }
    }, [choice.index, choice.type, onClick]);

    const Component = ChoiceRegistry.get(choice.type);

    // Build class list: start with choice classes (including inkweave-choice), add button style
    const classList = [...choice.classes, styles.button];

    // Add type-specific class if needed (e.g., disabled for unclickable)
    if (choice.type === "unclickable" && styles.disabled) {
      classList.push(styles.disabled);
    }

    // Remove duplicates and join
    const className = [...new Set(classList)].join(" ");

    if (Component) {
      return (
        <li style={{ "--index": index } as React.CSSProperties}>
          {createElement(Component, {
            choice,
            onClick: handleClick,
            className,
            children: choice.text,
          })}
        </li>
      );
    }

    return (
      <li className={styles.item} style={{ "--index": index } as React.CSSProperties}>
        <a
          onClick={handleClick}
          className={className}
          aria-disabled={choice.type === "unclickable"}
        >
          {choice.text}
        </a>
      </li>
    );
  },
  (prevProps, nextProps) => {
    return (
      prevProps.choice.index === nextProps.choice.index &&
      prevProps.choice.type === nextProps.choice.type &&
      prevProps.choice.text === nextProps.choice.text &&
      prevProps.choice.val === nextProps.choice.val
    );
  },
);
ChoiceItem.displayName = "ChoiceItem";

const ChoicesComponent = () => {
  const ink = useStory();
  const choices = choicesStore((state) => state.choices);
  const canShow = typeof ink.choicesCanShow === "boolean" ? ink.choicesCanShow : true;

  const inkRef = useRef(ink);
  inkRef.current = ink;

  const handleClick = useCallback((index: number) => {
    inkRef.current.choose(index);
  }, []);

  return (
    <ul
      data-inkweave="choices"
      className={`inkweave-choices ${styles.choices}`}
      key={canShow ? "visible" : "hidden"}
      style={{ visibility: canShow ? "visible" : "hidden" }}
    >
      {choices.map((choice: Choice, index: number) => (
        <ChoiceItem key={choice.index} choice={choice} index={index} onClick={handleClick} />
      ))}
    </ul>
  );
};

export default memo(ChoicesComponent);
